{{ $values := .Values}}
{{- if $values.ngcCredentials.password }}

apiVersion: v1
kind: Secret
data:
  key: {{ .Values.ngcCredentials.password |  quote }}
metadata:
  creationTimestamp: null
  name: {{ template "speech-squad.fullname" . }}-model-pullsecret

{{- end }}
