{{ $values := .Values}}
{{- if $values.ngcCredentials.password }}

apiVersion: v1
data:
  .dockerconfigjson: {{ template "ngcPullSecret" . }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ template "speech-squad.fullname" . }}-imagepullsecret
type: kubernetes.io/dockerconfigjson

{{- end }}
